server:
  port: 8080
  servlet:
    context-path: /

# 更换自己的数据库和表，本项目使用用户和资产作为例子
spring:
  shardingsphere:
    datasource:
      names: db01-master,db01-slave
      db01-master:
        jdbc-url: jdbc:mysql://localhost:3306/db?allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false
        username: root
        password: Vivian
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
      db01-slave:
        jdbc-url: jdbc:mysql://localhost:3306/db?allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false
        username: readonly
        password: vivian
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
    props:
      sql:
        show: true
    sharding:
      master-slave-rules:
        ds_db01:
          master-data-source-name: db01-master
          slave-data-source-names:
            - db01-slave
      default-data-source-name: ds_db01
      default-database-strategy:
        hint:
          algorithm-class-name: com.jiyu.conf.MyDatasourceRoutingAlgorithm
